//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EhiWebService.EhiService
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EhiServiceRequestData", Namespace="EhiServiceDataContract")]
    [System.SerializableAttribute()]
    public partial class EhiServiceRequestData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string RequestContent {
            get {
                return this.RequestContentField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestContentField, value) != true)) {
                    this.RequestContentField = value;
                    this.RaisePropertyChanged("RequestContent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EhiService.IEhiService")]
    public interface IEhiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/GetCitiesList", ReplyAction="http://tempuri.org/IEhiService/GetCitiesListResponse")]
        string GetCitiesList(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/GetServiceAreasList", ReplyAction="http://tempuri.org/IEhiService/GetServiceAreasListResponse")]
        string GetServiceAreasList(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/GetDistrictsList", ReplyAction="http://tempuri.org/IEhiService/GetDistrictsListResponse")]
        string GetDistrictsList(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/GetStoresList", ReplyAction="http://tempuri.org/IEhiService/GetStoresListResponse")]
        string GetStoresList(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/RegisterUser", ReplyAction="http://tempuri.org/IEhiService/RegisterUserResponse")]
        string RegisterUser(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/GetCarTypesList", ReplyAction="http://tempuri.org/IEhiService/GetCarTypesListResponse")]
        string GetCarTypesList(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/CalculateOrderPrice", ReplyAction="http://tempuri.org/IEhiService/CalculateOrderPriceResponse")]
        string CalculateOrderPrice(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/CreateOrder", ReplyAction="http://tempuri.org/IEhiService/CreateOrderResponse")]
        string CreateOrder(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/CancleOrder", ReplyAction="http://tempuri.org/IEhiService/CancleOrderResponse")]
        string CancleOrder(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/ValidateOrder", ReplyAction="http://tempuri.org/IEhiService/ValidateOrderResponse")]
        string ValidateOrder(EhiWebService.EhiService.EhiServiceRequestData requesetData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/GetOrdersList", ReplyAction="http://tempuri.org/IEhiService/GetOrdersListResponse")]
        string GetOrdersList(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/GetOrderDetail", ReplyAction="http://tempuri.org/IEhiService/GetOrderDetailResponse")]
        string GetOrderDetail(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/NotifyPayment", ReplyAction="http://tempuri.org/IEhiService/NotifyPaymentResponse")]
        string NotifyPayment(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/CreateNonRegOrder", ReplyAction="http://tempuri.org/IEhiService/CreateNonRegOrderResponse")]
        string CreateNonRegOrder(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/UserLogin", ReplyAction="http://tempuri.org/IEhiService/UserLoginResponse")]
        string UserLogin(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/GetDiscountsList", ReplyAction="http://tempuri.org/IEhiService/GetDiscountsListResponse")]
        string GetDiscountsList(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/GetAddedServicesList", ReplyAction="http://tempuri.org/IEhiService/GetAddedServicesListResponse")]
        string GetAddedServicesList(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/GetUserInfo", ReplyAction="http://tempuri.org/IEhiService/GetUserInfoResponse")]
        string GetUserInfo(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/CreateLongRentOrder", ReplyAction="http://tempuri.org/IEhiService/CreateLongRentOrderResponse")]
        string CreateLongRentOrder(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/UpdateLongRentOrder", ReplyAction="http://tempuri.org/IEhiService/UpdateLongRentOrderResponse")]
        string UpdateLongRentOrder(EhiWebService.EhiService.EhiServiceRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhiService/CancelLongRentOrder", ReplyAction="http://tempuri.org/IEhiService/CancelLongRentOrderResponse")]
        string CancelLongRentOrder(EhiWebService.EhiService.EhiServiceRequestData requestData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEhiServiceChannel : EhiWebService.EhiService.IEhiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EhiServiceClient : System.ServiceModel.ClientBase<EhiWebService.EhiService.IEhiService>, EhiWebService.EhiService.IEhiService {
        
        public EhiServiceClient() {
        }
        
        public EhiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EhiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EhiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EhiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCitiesList(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.GetCitiesList(requestData);
        }
        
        public string GetServiceAreasList(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.GetServiceAreasList(requestData);
        }
        
        public string GetDistrictsList(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.GetDistrictsList(requestData);
        }
        
        public string GetStoresList(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.GetStoresList(requestData);
        }
        
        public string RegisterUser(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.RegisterUser(requestData);
        }
        
        public string GetCarTypesList(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.GetCarTypesList(requestData);
        }
        
        public string CalculateOrderPrice(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.CalculateOrderPrice(requestData);
        }
        
        public string CreateOrder(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.CreateOrder(requestData);
        }
        
        public string CancleOrder(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.CancleOrder(requestData);
        }
        
        public string ValidateOrder(EhiWebService.EhiService.EhiServiceRequestData requesetData) {
            return base.Channel.ValidateOrder(requesetData);
        }
        
        public string GetOrdersList(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.GetOrdersList(requestData);
        }
        
        public string GetOrderDetail(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.GetOrderDetail(requestData);
        }
        
        public string NotifyPayment(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.NotifyPayment(requestData);
        }
        
        public string CreateNonRegOrder(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.CreateNonRegOrder(requestData);
        }
        
        public string UserLogin(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.UserLogin(requestData);
        }
        
        public string GetDiscountsList(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.GetDiscountsList(requestData);
        }
        
        public string GetAddedServicesList(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.GetAddedServicesList(requestData);
        }
        
        public string GetUserInfo(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.GetUserInfo(requestData);
        }
        
        public string CreateLongRentOrder(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.CreateLongRentOrder(requestData);
        }
        
        public string UpdateLongRentOrder(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.UpdateLongRentOrder(requestData);
        }
        
        public string CancelLongRentOrder(EhiWebService.EhiService.EhiServiceRequestData requestData) {
            return base.Channel.CancelLongRentOrder(requestData);
        }
    }
}
