//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class CoffeeinBeverage1
{
	public  void BoilWater()
	{
        Console.WriteLine("烧水");
	}

	public  void PrepareRecipe()
	{
        BoilWater();
        Brew();
        PourInCup();
        //有个判断方法来添加调料
        if (WantCondiments())
        {
            AddCondiments();
        }
	}
    /// <summary>
    /// 加入一个方法，用来判断是否需要加调料
    /// </summary>
    /// <returns></returns>
    public virtual bool WantCondiments()
    {
        return true;
    }

	public  void PourInCup()
	{
        Console.WriteLine("倒入杯子中");
	}

	public abstract void Brew();

	public abstract void AddCondiments();

  

}

