//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Coffee1 : CoffeeinBeverage1
{
	public override void Brew()
	{
        Console.WriteLine("冲咖啡");
		
	}

	public override void AddCondiments()
	{
        Console.WriteLine("加糖和牛奶");
	}

    public override bool WantCondiments()
    {
        return false;
    }

}

